#!/usr/bin/env ruby
################################################################################
#  Copyright 2007 Codehaus Foundation                                          #
#                                                                              #
#  Licensed under the Apache License, Version 2.0 (the "License");             #
#  you may not use this file except in compliance with the License.            #
#  You may obtain a copy of the License at                                     #
#                                                                              #
#     http://www.apache.org/licenses/LICENSE-2.0                               #
#                                                                              #
#  Unless required by applicable law or agreed to in writing, software         #
#  distributed under the License is distributed on an "AS IS" BASIS,           #
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.    #
#  See the License for the specific language governing permissions and         #
#  limitations under the License.                                              #
################################################################################
require 'lib/confluence4r/confluence4r.rb'

if ARGV.length != 4
  puts "Usage: dump-security URL USER PASS SPACE"
  puts "       dump-security http://confluence.example.com jim password thespace"
  exit 1
end

url, username, password, space_key = ARGV
space_key.upcase! #Space keys are always uppercase
confluence = Confluence::ConfluenceTool.new(1, url)
confluence.login(username, password)



space = confluence.getSpace(space_key)
page = confluence.getPage(space_key, 'Home')
puts "Page: #{page}.inspect"
puts confluence.getPagePermissions(page.id).inspect
